<a href="https://colab.research.google.com/github/JunetzMasihBelajar/2025_AI_TI1B/blob/main/Jobsheet4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 4: Pengolahan Data Menggunakan Pandas

## Latihan

### 1. Membaca berbagai format file menggunakan Pandas

#### a. Membaca file CSV

In [85]:
import pandas as pd

df = pd.read_csv('./data.csv')
print(df.to_string())
df
pd.options.display.max_rows

pd.options.display.max_rows = 9999

df = pd.read_csv('./data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### b. Membaca file JSON

In [86]:
import pandas as pd

df = pd.read_json('./data.json')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### c. Menggunakan Parameter pada Pandas Read

In [87]:
df = pd.read_csv('./data.csv', sep=',', header=0)
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

#### d. Membaca Custom Data

In [88]:
data = {
  "Duration":{
	  "0":60,
    "1":60,
    "2":60,
    "3":45
	},
	"Pulse":{
	  "0":110,
	  "1":117,
	  "2":103,
	  "3":109
	},
	"Maxpulse":{
	  "0":130,
	  "1":145,
	  "2":135,
	  "3":175
	},
	"Calories":{
	  "0":409,
	  "1":479,
	  "2":340,
	  "3":282
	}
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282

### 2. Membuat dan Mengakses Elemen Series

#### a. Membuat series dari sebuah List Python

In [89]:
import pandas as pd

li = [1, 7, 2]
se = pd.Series(li)
print(se)

0    1
1    7
2    2
dtype: int64

#### b. Mengakses Elemen pada series

In [90]:
li = [1, 7, 2]
se = pd.Series(li)

print(se[0])

1

#### c. Memberi Label pada Series

In [91]:
li = [1, 7, 2]
se = pd.Series(li, index = ["x", "y", "z"])

print(se['x'])

1

#### d. Membuat series dari Dictionary

In [92]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)

print(se)

day1    420
day2    380
day3    390
dtype: int64

### 3. Membuat DataFrame

#### a. Membuat DataFrame

In [93]:
import pandas as pd

df = pd.DataFrame(data={"Nama": ["Ali", "Joko", "Adi"],
                        "Umur": [12, 13, 15],
                        "Kelas": [6, 7, 8]})

df.columns
df.columns.values[0] = "Nama singkat"
print(df)

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
df

  Nama singkat  Umur  Kelas
0          Ali    12      6
1         Joko    13      7
2          Adi    15      8

   calories  duration
0       420        50
1       380        40
2       390        45

#### b. Mengakses elemen pada DataFrame

In [94]:
df.iloc[0:2, [0,1]]
df.iloc[0:2, 0:2]
df.iloc[:, 0:2]
df.loc[0:2, :'calories']
df.loc[0:2, ['calories', 'duration']]
df['calories']
df['calories'][0]
df[['calories']]
df[['calories']].loc[[0, 1]]

   calories
0       420
1       380

#### c. Memberi nama pada index

In [95]:
data = {
    "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

      calories  duration
day1       420        50
day2       380        40
day3       390        45

#### d. Melihat DataFrame

In [96]:
df = pd.read_csv('./data.csv')
print(df)
df
df.head()
df.tail()
df.head(10)
df.shape
df.dtypes

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

#### e. Membaca Informasi pada DataFrame

In [97]:
df.info()
df.describe
df['Calories'].mean(), df['Calories'].median(),
df['Calories'].mode()[0]

df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

## Tugas Praktikum

In [111]:
# No. 1
import pandas as pd

df = pd.read_csv('/content/epl-goalScorer(20-21).csv')
df

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,518,9423,Gaetano Berardi,2,113,0,0.074761,0,0.000000,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,519,9524,Anthony Elanga,1,67,0,0.000000,0,0.000000,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,520,9540,Femi Seriki,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,521,9552,Tyrese Francois,1,13,0,0.000000,0,0.000000,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

In [99]:
# No. 2
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [100]:
# No. 3
df.shape

(522, 19)

In [101]:
# No. 4
df.dtypes

Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

In [112]:
# No. 5
df[['player_name', 'goals']]

                player_name  goals
0                Harry Kane     23
1             Mohamed Salah     22
2           Bruno Fernandes     18
3             Son Heung-Min     17
4           Patrick Bamford     17
..                      ...    ...
517  Jaden Philogene-Bidace      0
518         Gaetano Berardi      0
519          Anthony Elanga      0
520             Femi Seriki      0
521         Tyrese Francois      0

[522 rows x 2 columns]

In [113]:
# No. 6
df[['player_name', 'goals', 'position', 'team_title', 'yellow_cards']]

                player_name  goals position         team_title  yellow_cards
0                Harry Kane     23        F          Tottenham             1
1             Mohamed Salah     22    F M S          Liverpool             0
2           Bruno Fernandes     18      M S  Manchester United             6
3             Son Heung-Min     17    F M S          Tottenham             0
4           Patrick Bamford     17      F S              Leeds             3
..                      ...    ...      ...                ...           ...
517  Jaden Philogene-Bidace      0        S        Aston Villa             0
518         Gaetano Berardi      0      D S              Leeds             0
519          Anthony Elanga      0        M  Manchester United             0
520             Femi Seriki      0        S   Sheffield United             0
521         Tyrese Francois      0        S             Fulham             0

[522 rows x 5 columns]

In [104]:
# No. 7
df[df['team_title'] == 'Liverpool']

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
16,16,838,Sadio Mané,35,2805,11,14.828548,7,7.787755,94,61,3,0,F M S,Liverpool,11,14.828548,24.998923,6.057656
26,26,482,Roberto Firmino,36,2882,9,12.860213,7,6.116863,83,44,2,0,F M S,Liverpool,9,12.860213,25.271458,10.198550
30,30,6854,Diogo Jota,19,1114,9,7.057721,0,1.762521,46,12,2,0,F M S,Liverpool,9,7.057721,10.972975,4.076096
116,116,771,Georginio Wijnaldum,38,2961,2,2.817427,0,1.662922,31,21,1,0,M S,Liverpool,2,2.817427,13.922182,10.476277
130,130,1791,Trent Alexander-Arnold,36,3040,2,2.593060,7,8.576368,55,77,2,0,D S,Liverpool,2,2.593060,23.107881,17.648908
161,161,229,Thiago Alcántara,24,1865,1,1.211306,0,2.554922,22,30,4,0,M S,Liverpool,1,1.211306,11.152549,9.468282
162,162,332,Joel Matip,10,701,1,0.784475,2,1.180275,5,3,2,0,D S,Liverpool,1,0.784475,4.383128,4.383128
172,172,605,Jordan Henderson,21,1710,1,1.135798,1,1.483709,14,14,0,0,D M S,Liverpool,1,1.135798,11.494361,10.461348
187,187,833,Virgil van Dijk,5,370,1,0.553383,0,0.000000,4,0,1,0,D,Liverpool,1,0.553383,1.409594,1.288435
192,192,966,Alex Oxlade-Chamberlain,13,238,1,0.300651,1,0.301778,8,2,0,0,F M S,Liverpool,1,0.300651,0.998663,0.766685
198,198,1257,Alisson,33,2970,1,0.107682,0,0.000000,1,0,1,0,GK,Liverpool,1,0.107682,3.559325,3.559325
204,204,1688,Andrew Robertson,38,3391,1,1.437934,7,7.220492,19,65,2,0,D,Liverpool,1,1.437934,19.869482,15.435009
226,226,6665,Curtis Jones,24,1174,1,1.758893,2,1.521144,19,12,2,0,M S,Liverpool,1,1.758893,7.742866,5.182874
251,251,8228,Nathaniel Phillips,17,1451,1,1.027709,1,0.916557,15,7,2,0,D S,Liverpool,1,1.027709,4.325661,4.156065
272,272,484,Divock Origi,9,176,0,1.081121,0,0.140035,7,2,0,0,F S,Liverpool,0,1.081121,1.496935,0.782366
274,274,489,James Milner,26,1037,0,0.356574,1,0.790560,12,13,3,0,D M S,Liverpool,0,0.356574,5.685045,4.885257
278,278,527,Adrián,3,270,0,0.000000,0,0.000000,0,0,0,0,GK,Liverpool,0,0.000000,0.397439,0.397439
330,330,888,Xherdan Shaqiri,14,534,0,0.424721,2,2.510420,11,19,2,0,F M S,Liverpool,0,0.424721,4.585736,2.122926
335,335,987,Joseph Gomez,7,594,0,0.000000,0,0.065429,0,1,0,0,D S,Liverpool,0,0.000000,2.085420,2.019991
375,375,3420,Fabinho,30,2563,0,0.362489,0,0.298062,10,4,6,0,D M S,Liverpool,0,0.362489,11.808026,11.555005
384,384,5247,Naby Keita,10,525,0,0.393259,0,0.912951,9,6,1,0,M S,Liverpool,0,0.393259,3.590221,2.329714
436,436,7376,Ozan Kabak,9,807,0,0.086028,0,0.029387,1,1,3,0,D,Liverpool,0,0.086028,1.863912,1.863912
453,453,7904,Caoimhin Kelleher,2,180,0,0.000000,0,0.000000,0,0,0,0,GK,Liverpool,0,0.000000,0.447927,0.447927
465,465,8204,Neco Williams,6,252,0,0.086225,0,0.193399,2,3,1,0,D S,Liverpool,0,0.086225,1.074642,0.795018
487,487,8852,Konstantinos Tsimikas,2,4,0,0.000000,0,0.000000,0,0,0,0,S,Liverpool,0,0.000000,0.000000,0.000000
498,498,9086,Rhys Williams,9,661,0,0.553240,0,0.222205,7,2,0,0,D S,Liverpool,0,0.553240,2.306016,2.187170

In [105]:
# No. 8
df[df['team_title'] == 'Arsenal']

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
9,9,3277,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941
19,19,318,Pierre-Emerick Aubameyang,28,2254,10,10.194089,3,2.352407,55,19,2,0,F M S,Arsenal,8,8.671751,14.778998,3.955129
36,36,5656,Nicolas Pepe,28,1512,8,5.811174,1,1.012160,43,11,1,1,F M S,Arsenal,7,5.050005,9.170708,4.217726
65,65,7322,Bukayo Saka,31,2561,5,7.169174,3,4.511791,61,38,1,0,D F M S,Arsenal,5,7.169174,18.292466,9.180440
140,140,5613,Gabriel,22,1904,2,1.550638,0,0.056096,15,2,2,1,D S,Arsenal,2,1.550638,5.588361,5.573927
146,146,6482,Eddie Nketiah,17,405,2,2.022099,1,0.742355,12,8,0,0,F S,Arsenal,2,2.022099,2.077280,0.220550
149,149,7230,Emile Smith-Rowe,19,1382,2,1.592160,4,3.449014,13,23,0,0,M S,Arsenal,2,1.592160,9.202460,5.454993
152,152,7752,Gabriel Martinelli,13,577,2,3.252450,1,1.745651,20,9,0,0,F M S,Arsenal,2,3.252450,6.159720,1.756597
160,160,204,Granit Xhaka,30,2447,1,0.711673,2,1.334161,18,14,7,1,D M S,Arsenal,1,0.711673,13.537367,12.521644
164,164,492,Héctor Bellerín,25,2098,1,0.860230,2,2.171512,15,21,8,0,D S,Arsenal,1,0.860230,8.059892,6.266996
165,165,496,Mohamed Elneny,23,1540,1,0.475616,0,0.256942,9,4,3,0,M S,Arsenal,1,0.475616,5.195761,4.651168
180,180,700,Willian,25,1413,1,1.834948,5,3.591710,20,32,0,0,F M S,Arsenal,1,1.834948,7.110169,3.815575
203,203,1676,David Luiz,20,1410,1,0.669567,0,0.524025,15,2,1,1,D S,Arsenal,1,0.669567,4.749539,4.629008
209,209,2517,Martin Odegaard,13,779,1,0.572077,1,1.678805,13,16,0,0,M S,Arsenal,1,0.572077,5.008195,4.034761
248,248,8089,Kieran Tierney,26,2215,1,0.386677,3,3.823889,15,31,4,0,D S,Arsenal,1,0.386677,8.525313,5.497776
267,267,181,Bernd Leno,34,3046,0,0.000000,0,0.000000,0,0,0,1,GK,Arsenal,0,0.000000,4.290661,4.290661
269,269,342,Sead Kolasinac,1,90,0,0.000000,0,0.000000,0,0,0,0,D,Arsenal,0,0.000000,0.429358,0.429358
275,275,508,Calum Chambers,9,660,0,0.363973,1,0.960840,8,9,0,0,D S,Arsenal,0,0.363973,3.650803,2.707076
322,322,847,Cédric Soares,10,746,0,0.203543,1,0.892805,7,6,1,0,D S,Arsenal,0,0.203543,3.335598,2.919357
348,348,1699,Shkodran Mustafi,3,43,0,0.000000,0,0.000000,0,0,0,0,S,Arsenal,0,0.000000,0.064725,0.064725
354,354,1749,Rob Holding,29,2458,0,0.733921,1,0.200683,14,4,2,0,D S,Arsenal,0,0.733921,7.343422,7.103263
366,366,2328,Thomas Partey,23,1453,0,0.957124,2,1.121045,22,12,5,0,M S,Arsenal,0,0.957124,7.060513,5.659220
369,369,2446,Dani Ceballos,25,1613,0,0.659258,3,2.578972,13,27,4,0,M S,Arsenal,0,0.659258,9.275826,8.116633
412,412,6492,Reiss Nelson,2,59,0,0.056917,0,0.000000,1,0,0,0,S,Arsenal,0,0.056917,0.348040,0.291123
423,423,6875,Rúnar Alex Rúnarsson,1,11,0,0.000000,0,0.000000,0,0,0,0,S,Arsenal,0,0.000000,0.000000,0.000000
473,473,8380,Pablo Marí,10,900,0,0.040523,0,0.054244,2,1,2,0,D,Arsenal,0,0.040523,3.604975,3.590738

In [106]:
# No. 9
df.nlargest(10, 'yellow_cards')[['player_name', 'yellow_cards']]

               player_name  yellow_cards
106            John McGinn            12
125          Harry Maguire            11
157        Conor Gallagher            11
259        Kalvin Phillips            10
110  Pierre-Emile Højbjerg             9
164        Héctor Bellerín             8
193          Mason Holgate             8
194              Luke Shaw             8
216       Luka Milivojevic             8
218          Yves Bissouma             8

In [107]:
# No. 10
df.nlargest(10, 'red_cards')[['player_name', 'red_cards']]

          player_name  red_cards
61         Lewis Dunk          2
7       Ollie Watkins          1
18    Matheus Pereira          1
21  Christian Benteke          1
25       Tomas Soucek          1
34        Neal Maupay          1
36       Nicolas Pepe          1
45        Richarlison          1
69    Anthony Martial          1
70        John Stones          1